Add many files in batches
cs50/lib50 pull request #66
Opened 2020-08-05 19:04 UTC by jsarchibald

This is a solution for #40 using the batching suggestion.

**Justification:**
"On a 32-bit Linux, this is ARGMAX/4-1 (32767). This becomes relevant if the average length of arguments is smaller than 4." -- https://www.in-ulm.de/~mascheck/various/argmax/

"On my OSX 10.5 machine (and most other BSD systems) it's 262144" -- https://serverfault.com/questions/69430/what-is-the-maximum-length-of-a-command-line-in-mac-os-x

Thus, this change adds files in batches of 32,700 (nice number, gives plenty of space for other arguments if needed, also pretty large so shouldn't slow the software excessively).

2020-08-10 18:44 UTC, kzidane commented
I think this is about the size of the command line not the number of arguments? i.e., you could still get `Argument list too long` even if you provide just one argument that's long enough.

If that's indeed the case, would it make sense to run `getconf ARG_MAX` first then batch add the files where the file names in each batch are <= that size?

2020-08-10 18:54 UTC, jsarchibald commented
> 
> 
> I think this is about the size of the command line not the number of arguments? i.e., you could still get `Argument list too long` even if you provide just one argument that's long enough.
> 
> If that's indeed the case, would it make sense to run `getconf ARG_MAX` to get the size of the max command-line first then batch add the files where the file names in each batch are <= that size?

That makes sense to me.

2020-08-10 21:20 UTC, jsarchibald commented
Made changes to base this on `getconf ARG_MAX` value @kzidane

2020-08-11 17:00 UTC, kzidane commented on lib50/_api.py
> +                    _run(git(f"add -f {' '.join(shlex.quote(f) for f in included[start:i])}"))
Would the last file in `included` get dropped here?

2020-08-11 20:17 UTC, jsarchibald commented on lib50/_api.py
> +                cl_limit = int(_run("getconf ARG_MAX")) // 16
This is what worked, experimentally. `ARG_MAX` delivers a value much higher than what actually works. Dividing by 16 is where that changes (dividing by 15 causes the error still).

2020-08-11 20:18 UTC, jsarchibald commented on lib50/_api.py
> +                cl_limit = 131072
That is the value from `getconf ARG_MAX // 16` for standard 64-bit Ubuntu.

2020-08-11 20:27 UTC, jsarchibald commented on lib50/_api.py
> +            cl_len = 60
Correct, it's to allow room for that. As for your question, can probably add a method to `Git` class that returns `self._args`, then calculate the length of each of those plus spaces and add to `len("git ")` (4).

2020-08-11 20:36 UTC, jsarchibald commented on lib50/_api.py
> +                    _run(git(f"add -f {' '.join(shlex.quote(f) for f in included[start:i])}"))
Yeah, should be `included[start:i - 1]` because the slice is inclusive.

And yeah, the last batch would be dropped if it didn't push `cl_len` over the limit. Simplest solution probably just to change line 501 to `if cl_len >= cl_limit or i + 1 == len(included)`, and increment `i` by one (so it's inclusive of the last item) if `i + 1 == len(included)`.

2020-08-11 20:38 UTC, kzidane commented on lib50/_api.py
> +                cl_limit = int(_run("getconf ARG_MAX")) // 16
Mmm we should probably figure out why. Does `_run` run the given command in a shell? Does the shell have a different limit maybe? Is there a way to get that limit if so?

2020-08-11 20:39 UTC, kzidane commented on lib50/_api.py
> +                cl_limit = 131072
We probably shouldn't rely on that since it could be different from one Unix-based system to another. Maybe fall back to adding them one by one or add all of them at once in this case?

2020-08-11 20:43 UTC, jsarchibald commented on lib50/_api.py
> +                cl_len += len(fl) + 1
Yes, it's for spaces. Quotes are only placed where needed with `shlex.quote` I think. So the only way to know for sure if something is quoted is to call `shlex.quote` which is kind of painful when we already do that for every file name when we add the batch. Alternatively, we could assume that every name is quoted and maybe end up with smaller batches as a result, and realistically that wouldn't be nearly as much of a performance drag as calling a function repeatedly. So I'm in favor of changing the `+ 1` to `+ 3` to be safe.

2020-08-11 20:47 UTC, kzidane commented on lib50/_api.py
> +                cl_len += len(fl) + 1
I mean we can just take the length of `shlex.quote(fl)` or whatever instead of `len(fl)` since we call `shlex.quote` on all files anyway? But is the size of quotes indeed included in the size of the command-line or does the shell just drop the quotes before storing the command-line?

2020-08-11 20:48 UTC, jsarchibald commented on lib50/_api.py
> +                cl_limit = 131072
Yeah, probably adding just adding them all at once is fine.

2020-08-11 20:51 UTC, jsarchibald commented on lib50/_api.py
> +                cl_len += len(fl) + 1
Yeah, what I meant was that we do the `shlex.quote` call inside a generator-style loop that happens when we run the batch right now (and thus *not* as we're doing the counting, which is in the same outer loop but not within the condition), but moving it to replace `included[i]` as part of the outer loop is probably the solution here so as to avoid doing the same operation twice needlessly.

2020-08-11 20:52 UTC, jsarchibald commented on lib50/_api.py
> +                cl_limit = int(_run("getconf ARG_MAX")) // 16
I did some research that wasn't very fruitful, but will do some more and let you know if I find anything useful.

2020-08-12 19:30 UTC, jsarchibald commented on lib50/_api.py
> +                cl_limit = int(_run("getconf ARG_MAX")) // 16
`_run` runs the command in a `pexpect.spawn` [call](https://github.com/pexpect/pexpect/blob/master/pexpect/pty_spawn.py#L303), which [calls](https://github.com/pexpect/pexpect/blob/master/pexpect/pty_spawn.py#L315) `PtyProcess.spawn`, which [calls](https://github.com/pexpect/ptyprocess/blob/master/ptyprocess/ptyprocess.py#L288) `os.execv` or `os.execvpe`, which [essentially](https://github.com/python/cpython/blob/master/Lib/os.py#L576) just calls the command line [execve](https://man7.org/linux/man-pages/man2/execve.2.html). So it seems to be an OS error, not anything related to how `_run` is written. This is also supported based on an experiment in which I generated commands and then ran them in an Ubuntu terminal.

Since the value that actually breaks Ubuntu command calls is (seemingly) arbitrary and not directly related to the value from `getconf ARG_MAX` (adding or subtracting a few characters after the division by 16 doesn't have an effect on whether the command can run) and this problem probably isn't due to the size of the environment (dividing `ARG_MAX` by 15 should certainly handle even really long envs, and ours, in testing, is much smaller than that would allow for -- I checked) I doubt the value of `ARG_MAX` at least for Ubuntu systems. I propose coming up with an arbitrary integer here and sticking to it (maybe 32768 to be safe?).

2020-12-12 02:10 UTC, cmlsharp requested changes

2020-12-12 02:10 UTC, cmlsharp commented on lib50/_api.py
> +                cl_limit = int(_run("getconf ARG_MAX")) // 16
This site literally recommends calling `exec` with longer and longer argument lists until it fails as the most reliable way. Yikes. Environment variables also count towards ARG_MAX.

https://www.in-ulm.de/~mascheck/various/argmax/

POSIX defines the minimum ARG_MAX to be 4096, we could just use that conservatively?

Also, this limit is in bytes, right? That might be the reason you are dividing by 16, the average length of the paths you are using is ~16 characters. That makes things a little more complicated to split. (the length of arguments now matters).

2021-08-08 05:19 UTC, closed without merging